# permissions for end users to edit springbootservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: springbootserver-editor-role
rules:
- apiGroups:
  - springbootsites.microsoft.com
  resources:
  - springbootservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - springbootsites.microsoft.com
  resources:
  - springbootservers/status
  verbs:
  - get
