# permissions for end users to view springbootdiscovereds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: springbootdiscovered-viewer-role
rules:
- apiGroups:
  - springbootsites.microsoft.com
  resources:
  - springbootdiscovereds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - springbootsites.microsoft.com
  resources:
  - springbootdiscovereds/status
  verbs:
  - get
