# permissions for end users to edit springbootdiscovereds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: springbootdiscovered-editor-role
rules:
- apiGroups:
  - springbootsites.microsoft.com
  resources:
  - springbootdiscovereds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - springbootsites.microsoft.com
  resources:
  - springbootdiscovereds/status
  verbs:
  - get
