namespace: springbootsites
replicaCount: 1

image:
  repository: qiaolei81/springboot-discovery-controller
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi


